annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed Helm chart value "zk.externalAddress"
      links:
        - name: Github Issue
          url: https://github.com/apache/solr-operator/issues/379
        - name: Github PR
          url: https://github.com/apache/solr-operator/pull/380
    - kind: fixed
      description: Fixed Helm chart value "addressability.external.additionalDomains", will be renamed to "additionalDomainNames" in v0.6.0
      links:
        - name: Github Issue
          url: https://github.com/apache/solr-operator/issues/412
        - name: Github PR
          url: https://github.com/apache/solr-operator/pull/415
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: solr
      image: solr:8.9
      whitelisted: true
  artifacthub.io/links: |
    - name: "Solr Source"
      url: https://github.com/apache/solr
    - name: "Helm Chart Source"
      url: https://github.com/apache/solr-operator
    - name: "Solr Documentation"
      url: https://solr.apache.org/guide/
    - name: "Solr on Kube Tutorials"
      url: https://solr.apache.org/operator/resources#tutorials
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/apache-solr/solr-operator
  artifacthub.io/signKey: |
    fingerprint: 50E3EE1C91C7E0CB4DFB007B369424FC98F3F6EC
    url: https://dist.apache.org/repos/dist/release/solr/KEYS
apiVersion: v2
appVersion: 8.9.0
description: A SolrCloud cluser running on Kubernetes via the Solr Operator
home: https://solr.apache.org
icon: https://solr.apache.org/theme/images/identity/Solr_Logo_on_white.png
keywords:
- solr
- apache
- search
- lucene
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: dev@solr.apache.org
  name: Solr Dev Community
- email: houston@apache.org
  name: Houston Putman
name: solr
sources:
- https://github.com/apache/solr
- https://github.com/apache/solr-operator
version: 0.5.1
